# 환경설정(어떤 db를 쓰고 db환경설정 etc)
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jsp
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
     
logging:
  level:
    org.hibernate.SQL: debug